### ISSUE TITLE
CSS Grid browser support

### ISSUE THREAD

**Issue by ghanbak** [ghanbak/seoyonmacdonald#2]
CSS Grid is breaking on Chrome due to invalid support and deprecated values.

Here's the new values and what it does:
Add this to [_events.scss](https://github.com/ghanbak/seoyonmacdonald/blob/e69dd2cf3544b1d04d77dc6a303b77cd32b128be/assets/css/scss/_events.scss#L9)
```css
.grid {
  grid-auto-columns: 1fr;
  grid-auto-rows: auto;
}
```

![image](https://user-images.githubusercontent.com/1842556/51622024-bc897a00-1f03-11e9-935e-6e24774f965b.png)

here's a before
![image](https://user-images.githubusercontent.com/1842556/51622049-c3b08800-1f03-11e9-9c7d-90f324b8dbe9.png)
